version: '3.6'

services:
  srvdb:
    image: postgres
    container_name: srvdb
    hostname: srvdb
    environment:
      POSTGRES_USER: consultas
      POSTGRES_DB: consultas
      POSTGRES_PASSWORD: QueryConSql.pwd
      TZ:  America/Guayaquil
    ports:
      - 5432:5432
    volumes:
      - pg_data2:/var/lib/postgresql/data

  srvwildfly:
    image: sanduchez
    container_name: srvwildfly
    hostname: srvwildfly
    environment:
      TZ:  America/Guayaquil
    ports:
      - 8082:8080
      - 8899:8009
      - 9992:9990
      - 8787:8787
    command: /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -c standalone.xml -bmanagement 0.0.0.0 --debug *:8787
    depends_on:
      - srvdb

  admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: info@jasoft.ec
      PGADMIN_DEFAULT_PASSWORD: clave
      TZ:  America/Guayaquil
    ports:
      - 5050:80
    depends_on:
      - srvdb

  swaggerui:
    depends_on:
      - srvwildfly
    image: swaggerapi/swagger-ui
    ports:
      - 8888:8080

  angular:
    depends_on:
      - srvwildfly  
    image: sanduchezang-app
    command: nginx -g 'daemon off;'
    ports:
      - 443:443
      - 80:80
    environment:
      - NGINX_SSL_CERT=/etc/ssl/certs/certificate.crt
      - NGINX_SSL_CERT_KEY=/etc/ssl/private/certificate.key
    volumes:
      - ./path/to/your/certificate.crt:/etc/ssl/certs/certificate.crt
      - ./path/to/your/private.key:/etc/ssl/private/certificate.key

volumes:
  pg_data2:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/adrian/datapg/
